version: "3"

volumes:
  db:
    driver: local

services:
  mysql:
    image: mysql:latest
    ports:
      - "3307:3306"
    volumes:
      - "db:/var/lib/mysql"
    environment:
      - "MYSQL_ROOT_PASSWORD=root"

  october:
    build: .
    volumes:
      - ./www:/var/www
    depends_on:
      - mysql
    ports:
      - "81:80"
